### ISSUE TITLE
Errors with HTTPS

### ISSUE THREAD

**Issue by tonyyanga** [projectarkc/arkc-client#2]
Hi,

Arkc is cool. Thank you and wish you good luck!

With your latest version, when I downloaded files via HTTPS I always encounter "netwwork failure", while I won't encounter that when using HTTP. It doesn't make sense. Can you please figure it out?

**Comment by tonyyanga** [comment]
BTW, better docs PLEASE!!!!!

**Comment by NoahArkc** [comment]
Thank you. We're fixing the problems you mentioned.

Hopefully you will find a satisfying verison when we release ArkC V0.1.2.

Best regards,

Sincerely,
Noah

**Comment by NoahArkc** [comment]
Hi, tonyyanga,

We believe we have fixed the HTTPS network failure issue, and please check the latest beta4 version at server / client side.

I recommend you to use our GUI [https://github.com/projectarkc/arkc-client-GUI-dotnet/](url) to simplify your configuration with the client side. The server-side configuration is pretty straightforward.

We will try to improve documentation in our stable release. Thank you for your attention.
