### ISSUE TITLE
Problems in your wiki

### ISSUE THREAD

**Issue by nebulakl** [projectarkc/arkc-client#4]
https://github.com/projectarkc/arkc-client/wiki/ArkC%E5%8D%8F%E8%AE%AE
In your image:
1. "Censured" should be "Censored", and "censurers" should be "censors"
Censure: (verb) to criticize or reproach in a harsh or vehement manner.
Censor: (verb) to delete (a word or passage of text) in one's capacity as a censor.
(noun) an official who examines books, plays, news reports, motion pictures, radio and television programs, letters, cablegrams, etc., for the purpose of suppressing parts deemed objectionable on moral, political, military, or other grounds.
[Source: http://www.dictionary.com/]
2. You should use the same font for two "Anonymous Proxy".

**Comment by NoahArkc** [comment]
Thank you. We will fix them soon.

Best regards,

Sincerely,
Noah

**Comment by NoahArkc** [comment]
Thank you. The diagrams are updated.
